name: Bug Report
description: File a bug report
title: "[Issue] Summary here)"

body:
  - type: markdown
    attributes:
      value: |
        # Instructions
        
        Please follow the instructions below. Failure to do so may result in your issue being closed.
        
        1. Provide a good title starting with [BUG].
        2. Fill out all sections of this bug report form.

  - type: markdown
    attributes:
      value: |
        # Details

  - type: textarea
    attributes:
      label: Summary of issue
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        It doesn't work.
    validations:
      required: true

